global:
  scrape_interval: 15s # Scrape targets metrics every 15 sec
  scrape_timeout: 10s # Wait time for a target scrape to finish at 10 sec
  evaluation_interval: 15s # 15 sec to evaluate rule

scrape_configs: # Scrape configuration for different jobs
  - job_name: "prometheus"
    honor_timestamps: true # Prometheus, by default will use the timestamps provided by targets for this job.
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "pihole"
    static_configs:
      - targets: ["pihole-exporter:9617"]
    metrics_path: /metrics
  - job_name: "node_exporter:9100"
    static_configs:
      - targets: ["node_exporter:9100"]
  - job_name: "mac_mini"
    static_configs:
      - targets: ["doimini.local:9100"]
